### ISSUE TITLE
Opinion on wireframe of Main 

### ISSUE THREAD

**Issue by austinprog** [austinprog/Find_Your_Youtuber#17]
What do you think? If you like this I will code it. (If you dont like it I will still code it :D)
![wireframe](https://cloud.githubusercontent.com/assets/7500568/7606719/0d670c10-f921-11e4-9887-fd8ce4c7d2ff.PNG)

**Comment by Vectrex33** [comment]
Looks fine.

**Comment by austinprog** [comment]
Approved

**Comment by Vectrex33** [comment]
You suddenly feel the urge to explode
