### ISSUE TITLE
Work on improved version of algorithm to pick a Youtuber

### ISSUE THREAD

**Issue by austinprog** [austinprog/Find_Your_Youtuber#5]

**Comment by austinprog** [comment]
This will be released in the V 0.3-Alpha, BUT will play a huge part in the GUI version when we get to that. So take your time on this as it is gonna be very important for the entire project in the future. Lets focus on the other enhancements for V0.2-Beta which is gonna be released Sunday April 5th 2015 as those are the most important. I labeled the ones that are gonna be V0.2

**Comment by austinprog** [comment]
Also the real deadline is gonna be by Midnight Saturday April 4th 2015, to start doing final testing, and the product will be on Raspberry Pi on Sunday at midnight if everything goes as planned :D

**Comment by austinprog** [comment]
Due to inactivity I am taking over this bug.

**Comment by Vectrex33** [comment]
Well, excuse me, princess. I suck at algorithms.

**Comment by austinprog** [comment]
No longer needed for V0.1.1 for obvious reasons going into V0.1.2
